### PR TITLE
add rate limiting with flask_limiter

### PR DESCRIPTION
**Pull request by suBDavis**
Opening to discuss code.

### CODE REVIEW

**Comment by suBDavis** [comment]
Looking good.  Maybe try adding some unit tests since I'm obsessed with travis now?

**Comment by alex-wyc** [comment]
Ok I'll add some unit tests, but also are the tentative rates good? Then again they are all in settings so can be changed at deploy time.

**Comment by suBDavis** [comment]
Yeah I think the rates are perfect.  Great job separating them out by cost.

**Comment by suBDavis** [comment]
BTW this code is now live @ dev.memetrades.com

**Pull request merged**
